import "./globals.css";

import Header from "../components/header";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />

        <div className="flex bg-yellow-100 h-screen">
          <Sidebar />
          <div className="bg-slate-500 w-full">{children}</div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
